In [ ]:
# Load datasets
import pandas as pd
customers= pd.read_csv('customers.csv')
orders= pd.read_csv('orders.csv')
products= pd.read_csv('products.csv')
sales= pd.read_csv('sales.csv')

In [ ]:
# Preview dataset
orders.head()

   order_id  customer_id  payment order_date delivery_date
0         1           64    30811  2021-8-30    2021-09-24
1         2          473    50490   2021-2-3    2021-02-13
2         3          774    46763  2021-10-8    2021-11-03
3         4          433    39782   2021-5-6    2021-05-19
4         5          441    14719  2021-3-23    2021-03-24

In [ ]:
# Execute analysis step
orders.columns

Index(['order_id', 'customer_id', 'payment', 'order_date', 'delivery_date'], dtype='object')

In [ ]:
# Display dataset info
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1000 non-null   int64
 1   customer_id    1000 non-null   int64
 2   payment        1000 non-null   int64
 3   order_date     1000 non-null   object
 4   delivery_date  1000 non-null   object
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [ ]:
# Check missing values
orders.isnull().sum()

order_id         0
customer_id      0
payment          0
order_date       0
delivery_date    0
dtype: int64

In [ ]:
# Execute analysis step
orders.dtypes

order_id          int64
customer_id       int64
payment           int64
order_date       object
delivery_date    object
dtype: object

In [ ]:
# Execute analysis step
orders['order_date'] = pd.to_datetime(orders['order_date'])
orders['delivery_date'] = pd.to_datetime(orders['delivery_date'])

orders['delivery_time'] = orders['delivery_date'] - orders['order_date']
orders.dtypes

order_id                   int64
customer_id                int64
payment                    int64
order_date        datetime64[ns]
delivery_date     datetime64[ns]
delivery_time    timedelta64[ns]
dtype: object

In [ ]:
# Execute analysis step
orders.duplicated().sum()

np.int64(0)

In [ ]:
# Preview dataset
orders.head()

   order_id  customer_id  payment order_date delivery_date delivery_time
0         1           64    30811 2021-08-30    2021-09-24       25 days
1         2          473    50490 2021-02-03    2021-02-13       10 days
2         3          774    46763 2021-10-08    2021-11-03       26 days
3         4          433    39782 2021-05-06    2021-05-19       13 days
4         5          441    14719 2021-03-23    2021-03-24        1 days

In [ ]:
# Execute analysis step
from google.colab import files

# DataFrame'i yeni CSV dosyası olarak kaydet
orders.to_csv("orders_updated.csv", index=False)

# Dosyayı bilgisayarına indir
files.download("orders_updated.csv")